[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NEXT_PUBLIC_API_BASE_URL = "https://skdjangobackend-production.up.railway.app"
NEXT_PUBLIC_NODE_ENV = "production"
PORT = "3000" 